import 'package:get/get.dart';
// Export everything from GetX so that it's available globally via localization_service.dart
export 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      'Timetable': 'Timetable',
      'Ramzan': 'Ramzan',
      'Qibla': 'Qibla',
      'Dua': 'Dua',
      'Tasbih': 'Tasbih',
      'Salatuk Options': 'Salatuk Options',
      'Settings': 'Settings',
      'Namaz Tarika': 'Namaz Tarika',
      'Fatiha Ka Tarika': 'Fatiha Ka Tarika',
      'Calendar': 'Calendar',
      'About App': 'About App',
      'Appearance': 'Appearance',
      'Dark Mode': 'Dark Mode',
      'Alarm & Times': 'Alarm & Times',
      'Ring Adhan time': 'Ring Adhan time',
      'Set Manual Prayer Times': 'Set Manual Prayer Times',
      'Prayer Notifications': 'Prayer Notifications',
      'Location updated': 'Location updated',
      'Advanced Prayer Calculation': 'Advanced Prayer Calculation',
      'Calculation Method': 'Calculation Method',
      'Asr Method (Juristic)': 'Asr Method (Juristic)',
      'Hijri Date Adjustment': 'Hijri Date Adjustment',
      '-2 Days': '-2 Days',
      '-1 Day': '-1 Day',
      '0 Days (No offset)': '0 Days (No offset)',
      '+1 Day': '+1 Day',
      '+2 Days': '+2 Days',
      'Not Set': 'Not Set',
      'Location: ': 'Location: ',
      'Fajr': 'Fajr',
      'Sunrise': 'Sunrise',
      'Sunset': 'Sunset',
      'Dhuhr': 'Dhuhr',
      'Asr': 'Asr',
      'Maghrib': 'Maghrib',
      'Isha': 'Isha',
      'Jummah': 'Jummah',
      'Jumah': 'Jummah',
      'Sehr': 'Sehr',
      'Iftar': 'Iftar',
      'Next Prayer': 'Next Prayer',
      'Manual Mode': 'Manual Mode',
      'Hijri': 'Hijri',
      'Reset': 'Reset',
      'Count': 'Count',
      'Total Count': 'Total Count',
      'Daily Count': 'Daily Count',
      'Minus': 'Minus',
      'Home': 'Home',
      'Prayer': 'Prayer',
      'Daily Ayah': 'Daily Ayah',
      'Daily Dua': 'Daily Dua',
      'Daily Hadith': 'Daily Hadith',
      '👉 Welcome to Salatuk Timetable • Daily Salah & Ramzan Updates • Please keep your phone on silent 📵 during Jamaat • 🤲 Pray on time to be successful in both worlds • May Allah 🕋 accept our prayers • JazakAllah Khair':
          '👉 Welcome to Salatuk Timetable • Daily Salah & Ramzan Updates • Please keep your phone on silent 📵 during Jamaat • 🤲 Pray on time to be successful in both worlds • May Allah 🕋 accept our prayers • JazakAllah Khair',
      'Error loading times': 'Error loading times',
      'Ramzan Timetable': 'Ramzan Timetable',
      'SEHR': 'SEHR',
      'IFTAR': 'IFTAR',
      'COUNT': 'COUNT',
      'Rakats Details:': 'Rakats Details:',
      'Urdu Niyyat (نیت):': 'Urdu Niyyat (نیت):',
      'Hindi Niyyat (नीयत):': 'Hindi Niyyat (नीयत):',
      'PRAYER': 'PRAYER',
      'AZAN': 'AZAN',
      'JAMAAT': 'JAMAAT',
      'ENDS': 'ENDS',
      'English': 'English',
      'Reset Total Count?': 'Reset Total Count?',
      'Reset Total Count': 'Reset Total Count',
      'Are you sure you want to reset your lifetime tasbih progress?':
          'Are you sure you want to reset your lifetime tasbih progress?',
      'Cancel': 'Cancel',
      'Prayer Azan & Jamaat Time': 'Prayer Azan & Jamaat Time',
      'Override default API times': 'Override default API times',
      'Prayer Override': 'Prayer Override',
      'Azan Time': 'Azan Time',
      'Jamaat Time': 'Jamaat Time',
      'API Default': 'API Default',
      'Reset to Default?': 'Reset to Default?',
      'This will clear all manual times and use API defaults.':
          'This will clear all manual times and use API defaults.',
      'Success': 'Success',
      'All times reset to default': 'All times reset to default',
      'Fajr End': 'Fajr End',
      'Dhuhr End': 'Dhuhr End',
      'Asr End': 'Asr End',
      'Maghrib End': 'Maghrib End',
      'Isha End': 'Isha End',
      'SubhanAllah': 'SubhanAllah',
      'Alhamdulillah': 'Alhamdulillah',
      'Allahu Akbar': 'Allahu Akbar',
      'Master Sound Toggle': 'Master Sound Toggle',
      'Enable or disable all Azan/Jamat sounds': 'Enable or disable all Azan/Jamat sounds',
      'Show/Hide individual prayer settings': 'Show/Hide individual prayer settings',
      'Azan & Jamaat Time': 'Azan & Jamaat Time',
      'Override default times': 'Override default times',
      'Prayer Calculation': 'Prayer Calculation',
      'Show advanced settings': 'Show advanced settings',
      'University of Islamic Sciences, Karachi': 'University of Islamic Sciences, Karachi',
      'Islamic Society of North America (ISNA)': 'Islamic Society of North America (ISNA)',
      'Muslim World League': 'Muslim World League',
      'Umm Al-Qura University, Makkah': 'Umm Al-Qura University, Makkah',
      'Egyptian General Authority of Survey': 'Egyptian General Authority of Survey',
      'Gulf Region': 'Gulf Region',
      'Kuwait': 'Kuwait',
      'Qatar': 'Qatar',
      'Majlis Ugama Islam Singapura, Singapore': 'Majlis Ugama Islam Singapura, Singapore',
      'Standard (Shafi\'i, Maliki, Hanbali)': 'Standard (Shafi\'i, Maliki, Hanbali)',
      'Hanafi': 'Hanafi',
      'Dua copied': 'Dua copied',
      'Link copied': 'Link copied',
      'Copy': 'Copy',
      'Share': 'Share',
      'Location Settings': 'Location Settings',
      'Auto Detect Location': 'Auto Detect Location',
      'Area': 'Area',
      'City': 'City',
      'State': 'State',
      'Country': 'Country',
      'Pincode': 'Pincode',
      'Save': 'Save',
      'Could not obtain GPS location': 'Could not obtain GPS location',
      'Please enter city and country': 'Please enter city and country',
      'Lifetime Progress': 'Lifetime Progress',
      'BEADS': 'BEADS',
      'End - ': 'End - ',
      'End': 'End',
      'Prayer Times & Qibla Direction app.': 'Prayer Times & Qibla Direction app.',
      'Developer Details': 'Developer Details',
      'Name': 'Name',
      'Email': 'Email',
      'Phone': 'Phone',
      'UPCOMING SALAH': 'UPCOMING SALAH',
      'Upcoming': 'Upcoming',
      'Next Salah Begins In': 'Next Salah Begins In',
      'Monday': 'Monday',
      'Tuesday': 'Tuesday',
      'Wednesday': 'Wednesday',
      'Thursday': 'Thursday',
      'Friday': 'Friday',
      'Saturday': 'Saturday',
      'Sunday': 'Sunday',
      'Mon': 'Mon',
      'Tue': 'Tue',
      'Wed': 'Wed',
      'Thu': 'Thu',
      'Fri': 'Fri',
      'Sat': 'Sat',
      'Sun': 'Sun',
      'Muharram': 'Muharram',
      'Safar': 'Safar',
      'Rabi\' al-awwal': 'Rabi\' al-awwal',
      'Rabi\' al-thani': 'Rabi\' al-thani',
      'Jumada al-ula': 'Jumada al-ula',
      'Jumada al-akhira': 'Jumada al-akhira',
      'Rajab': 'Rajab',
      'Sha\'ban': 'Sha\'ban',
      'Ramadan': 'Ramadan',
      'Shawwal': 'Shawwal',
      'Dhu al-Qi\'dah': 'Dhu al-Qi\'dah',
      'Dhu al-Hijjah': 'Dhu al-Hijjah',
      'View both English and Hijri dates easily for the whole month.':
          'View both English and Hijri dates easily for the whole month.',
      'Our Lord, give us in this world [that which is] good and in the Hereafter [that which is] good and protect us from the punishment of the Fire.':
          'Our Lord, give us in this world [that which is] good and in the Hereafter [that which is] good and protect us from the punishment of the Fire.',
      'He who does not show mercy to others, Allah will not show mercy to him.':
          'He who does not show mercy to others, Allah will not show mercy to him.',
      'Ayatul Kursi': 'Ayatul Kursi',
      'Allah - there is no deity except Him, the Ever-Living, the Sustainer of [all] existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is [presently] before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His Kursi extends over the heavens and the earth, and their preservation tires Him not. And He is the Most High, the Most Great.':
          'Allah - there is no deity except Him, the Ever-Living, the Sustainer of [all] existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is [presently] before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His Kursi extends over the heavens and the earth, and their preservation tires Him not. And He is the Most High, the Most Great.',
      'Say, "He is Allah, [who is] One, Allah, the Eternal Refuge. He neither begets nor is born, Nor is there to Him any equivalent."':
          'Say, "He is Allah, [who is] One, Allah, the Eternal Refuge. He neither begets nor is born, Nor is there to Him any equivalent."',
      'Say, "I seek refuge in the Lord of daybreak From the evil of that which He created And from the evil of darkness when it settles And from the evil of the blowers in knots And from the evil of an envier when he envies."':
          'Say, "I seek refuge in the Lord of daybreak From the evil of that which He created And from the evil of darkness when it settles And from the evil of the blowers in knots And from the evil of an envier when he envies."',
      'Say, "I seek refuge in the Lord of mankind, The Sovereign of mankind, The God of mankind, From the evil of the retreating whisperer - Who whispers [evil] into the breasts of mankind - From among the jinn and mankind."':
          'Say, "I seek refuge in the Lord of mankind, The Sovereign of mankind, The God of mankind, From the evil of the retreating whisperer - Who whispers [evil] into the breasts of mankind - From among the jinn and mankind."',
      'Say, "O disbelievers, I do not worship what you worship. Nor are you worshippers of what I worship. Nor will I be a worshipper of what you have worshipped. Nor will you be worshippers of what I worship. For you is your religion, and for me is my religion."':
          'Say, "O disbelievers, I do not worship what you worship. Nor are you worshippers of what I worship. Nor will I be a worshipper of what you have worshipped. Nor will you be worshippers of what I worship. For you is your religion, and for me is my religion."',
      'In the name of Allah, the Entirely Merciful, the Especially Merciful. [All] praise is [due] to Allah, Lord of the worlds - The Entirely Merciful, the Especially Merciful, Sovereign of the Day of Recompense. It is You we worship and You we ask for help. Guide us to the straight path - The path of those upon whom You have bestowed favor, not of those who have evoked [Your] anger or of those who are astray.':
          'In the name of Allah, the Entirely Merciful, the Especially Merciful. [All] praise is [due] to Allah, Lord of the worlds - The Entirely Merciful, the Especially Merciful, Sovereign of the Day of Recompense. It is You we worship and You we ask for help. Guide us to the straight path - The path of those upon whom You have bestowed favor, not of those who have evoked [Your] anger or of those who are astray.',
      'My Lord, increase me in knowledge.': 'My Lord, increase me in knowledge.',
      'My Lord, have mercy upon them as they brought me up [when I was] small.':
          'My Lord, have mercy upon them as they brought me up [when I was] small.',
      'Detected:': 'Detected:',
      'Qibla Direction': 'Qibla Direction',
      'Qibla Angle': 'Qibla Angle',
      'Distance': 'Distance',
      'Align the needle to the top of the compass to face the Qibla directly.':
          'Align the needle to the top of the compass to face the Qibla directly.',
      '2 Rakats Sunnah (Muakkadah)\n2 Rakats Fard\nTotal: 4 Rakats':
          '2 Rakats Sunnah (Muakkadah)\n2 Rakats Fard\nTotal: 4 Rakats',
      '4 Rakats Sunnah (Muakkadah)\n4 Rakats Fard\n2 Rakats Sunnah (Muakkadah)\n2 Rakats Nafl\nTotal: 12 Rakats':
          '4 Rakats Sunnah (Muakkadah)\n4 Rakats Fard\n2 Rakats Sunnah (Muakkadah)\n2 Rakats Nafl\nTotal: 12 Rakats',
      '4 Rakats Sunnah (Ghair Muakkadah)\n4 Rakats Fard\nTotal: 8 Rakats':
          '4 Rakats Sunnah (Ghair Muakkadah)\n4 Rakats Fard\nTotal: 8 Rakats',
      '3 Rakats Fard\n2 Rakats Sunnah (Muakkadah)\n2 Rakats Nafl\nTotal: 7 Rakats':
          '3 Rakats Fard\n2 Rakats Sunnah (Muakkadah)\n2 Rakats Nafl\nTotal: 7 Rakats',
      '4 Rakats Sunnah (Ghair Muakkadah)\n4 Rakats Fard\n2 Rakats Sunnah (Muakkadah)\n2 Rakats Nafl\n3 Rakats Witr\n2 Rakats Nafl\nTotal: 17 Rakats':
          '4 Rakats Sunnah (Ghair Muakkadah)\n4 Rakats Fard\n2 Rakats Sunnah (Muakkadah)\n2 Rakats Nafl\n3 Rakats Witr\n2 Rakats Nafl\nTotal: 17 Rakats',
      '4 Rakats Sunnah (Muakkadah)\n2 Rakats Fard\n4 Rakats Sunnah (Muakkadah)\n2 Rakats Sunnah (Muakkadah)\n2 Rakats Nafl\nTotal: 14 Rakats':
          '4 Rakats Sunnah (Muakkadah)\n2 Rakats Fard\n4 Rakats Sunnah (Muakkadah)\n2 Rakats Sunnah (Muakkadah)\n2 Rakats Nafl\nTotal: 14 Rakats',
      'Step 1: Durood Shareef': 'Step 1: Durood Shareef',
      'Read Durood Shareef 3, 5, 7, or 11 times. (e.g., Durood-e-Ibrahimi)':
          'Read Durood Shareef 3, 5, 7, or 11 times. (e.g., Durood-e-Ibrahimi)',
      'Step 2: Surah Al-Kafirun (1 time)': 'Step 2: Surah Al-Kafirun (1 time)',
      'Read Surah Al-Kafirun 1 time.': 'Read Surah Al-Kafirun 1 time.',
      'Step 3: Surah Al-Ikhlas (3 times)': 'Step 3: Surah Al-Ikhlas (3 times)',
      'Read Surah Al-Ikhlas (Qul Huwa Allahu Ahad) 3 times.':
          'Read Surah Al-Ikhlas (Qul Huwa Allahu Ahad) 3 times.',
      'Step 4: Surah Al-Falaq (1 time)': 'Step 4: Surah Al-Falaq (1 time)',
      'Read Surah Al-Falaq 1 time.': 'Read Surah Al-Falaq 1 time.',
      'Step 5: Surah An-Nas (1 time)': 'Step 5: Surah An-Nas (1 time)',
      'Read Surah An-Nas 1 time.': 'Read Surah An-Nas 1 time.',
      'Step 6: Surah Al-Fatiha (1 time)': 'Step 6: Surah Al-Fatiha (1 time)',
      'Read Surah Al-Fatiha (Alhamdulillah) 1 time.':
          'Read Surah Al-Fatiha (Alhamdulillah) 1 time.',
      'Step 7: Surah Al-Baqarah (Beginning)': 'Step 7: Surah Al-Baqarah (Beginning)',
      'Read the first 5 Ayats of Surah Al-Baqarah.': 'Read the first 5 Ayats of Surah Al-Baqarah.',
      'Step 8: Final Durood and Dua': 'Step 8: Final Durood and Dua',
      'Recite Durood Shareef again 3, 5, 7 or 11 times. Then raise your hands in Dua and ask Allah to accept it and present the reward (Esaal-e-Sawab) to the beloved Prophet (PBUH), his family, companions, all Awliya Allah, and all deceased Muslims.':
          'Recite Durood Shareef again 3, 5, 7 or 11 times. Then raise your hands in Dua and ask Allah to accept it and present the reward (Esaal-e-Sawab) to the beloved Prophet (PBUH), his family, companions, all Awliya Allah, and all deceased Muslims.',
      'Arabi (عربی)': 'Arabi (Arabic)',
      'Hindi (हिंदी)': 'Hindi (Hindi)',
    },
    'ur': {
      'Timetable': 'ٹائم ٹیبل',
      'Ramzan': 'رمضان',
      'Qibla': 'قبلہ',
      'Dua': 'دعا',
      'Tasbih': 'تسبیح',
      'Salatuk Options': 'صلاتک کے اختیارات',
      'Settings': 'ترتیبات',
      'Namaz Tarika': 'نماز کا طریقہ',
      'Fatiha Ka Tarika': 'فاتحہ کا طریقہ',
      'Calendar': 'تقویم (کیلنڈر)',
      'About App': 'ایپ کے بارے میں',
      'Appearance': 'ظاہری شکل',
      'Dark Mode': 'ڈارک موڈ',
      'Alarm & Times': 'الارم اور اوقات',
      'Ring Adhan time': 'اذان کے وقت بجائیں',
      'Set Manual Prayer Times': 'دستی نماز کے اوقات متعین کریں',
      'Prayer Notifications': 'نماز کی اطلاعات',
      'Location updated': 'مقام اپ ڈیٹ ہو گیا',
      'Advanced Prayer Calculation': 'نماز کا تفصیلی حساب',
      'Calculation Method': 'حساب کا طریقہ',
      'Asr Method (Juristic)': 'عصر کا طریقہ (فقہی)',
      'Hijri Date Adjustment': 'ہجری تاریخ کی ترتیب',
      '-2 Days': '-2 دن',
      '-1 Day': '-1 دن',
      '0 Days (No offset)': '0 دن (کوئی تبدیلی نہیں)',
      '+1 Day': '+1 دن',
      '+2 Days': '+2 دن',
      'Not Set': 'طے نہیں کیا',
      'Location: ': 'مقام: ',
      'Fajr': 'فجر',
      'Sunrise': 'طلوع آفتاب',
      'Sunset': 'غروب آفتاب',
      'Dhuhr': 'ظہر',
      'Asr': 'عصر',
      'Maghrib': 'مغرب',
      'Isha': 'عشاء',
      'Jummah': 'جمعہ',
      'Jumah': 'جمعہ',
      'Sehr': 'سحر',
      'Iftar': 'افطار',
      'Next Prayer': 'اگلی نماز',
      'Manual Mode': 'دستی موڈ',
      'Hijri': 'ہجری',
      'Reset': 'ری سیٹ',
      'Count': 'گنتی',
      'Total Count': 'کل گنتی',
      'Daily Count': 'آج کی گنتی',
      'Minus': 'کم کریں',
      'Home': 'ہوم',
      'Prayer': 'نماز',
      'Daily Ayah': 'آج کی آیت',
      'Daily Dua': 'آج کی دعا',
      'Daily Hadith': 'آج کی حدیث',
      '👉 Welcome to Salatuk Timetable • Daily Salah & Ramzan Updates • Please keep your phone on silent 📵 during Jamaat • 🤲 Pray on time to be successful in both worlds • May Allah 🕋 accept our prayers • JazakAllah Khair':
          '👉 صلاتک ٹائم ٹیبل میں خوش آمدید • روزانہ نماز اور رمضان اپ ڈیٹس • براہ کرم جماعت کے دوران اپنا فون سائلنٹ 📵 پر رکھیں • 🤲 دونوں جہانوں میں کامیابی کے لیے وقت پر نماز پڑھیں • اللہ تعالیٰ 🕋 ہماری دعائیں قبول فرمائے • جزاک اللہ خیر',
      'Error loading times': 'اوقات لوڈ کرنے میں غلطی',
      'Ramzan Timetable': 'رمضان ٹائم ٹیبل',
      'SEHR': 'سحر',
      'IFTAR': 'افطار',
      'COUNT': 'گنتی',
      'Rakats Details:': 'رکعت کی تفصیلات:',
      'Urdu Niyyat (نیت):': 'اردو نیت:',
      'Hindi Niyyat (नीयت):': 'ہندی نیت:',
      'PRAYER': 'نماز',
      'AZAN': 'اذان',
      'JAMAAT': 'جماعت',
      'ENDS': 'ختم',
      'English': 'انگریزی',
      'Reset Total Count?': 'کل گنتی ری سیٹ کریں؟',
      'Reset Total Count': 'کل گنتی ری سیٹ کریں',
      'Are you sure you want to reset your lifetime tasbih progress?':
          'کیا آپ واقعی اپنی زندگی بھر کی تسبیح کی پیشرفت کو ری سیٹ کرنا چاہتے ہیں؟',
      'Cancel': 'منسوخ کریں',
      'SubhanAllah': 'سبحان اللہ',
      'Alhamdulillah': 'الحمدللہ',
      'Allahu Akbar': 'اللہ اکبر',
      'Master Sound Toggle': 'ماسٹر ساؤنڈ ٹوگل',
      'Enable or disable all Azan/Jamat sounds': 'تمام اذان اور جماعت کی آوازیں کھولیں یا بند کریں',
      'Show/Hide individual prayer settings': 'نماز کی انفرادی ترتیبات دکھائیں یا چھپائیں',
      'Azan & Jamaat Time': 'اذان اور جماعت کا وقت',
      'Override default times': 'پہلے سے طے شدہ اوقات تبدیل کریں',
      'Prayer Calculation': 'نماز کا حساب',
      'Show advanced settings': 'اعلی درجے کی ترتیبات دکھائیں',
      'University of Islamic Sciences, Karachi': 'جامعہ العلوم الاسلامیہ، کراچی',
      'Islamic Society of North America (ISNA)': 'اسلامک سوسائٹی آف نارتھ امریکہ (ISNA)',
      'Muslim World League': 'رابطہ عالم اسلامی',
      'Umm Al-Qura University, Makkah': 'ام القریٰ یونیورسٹی، مکہ',
      'Egyptian General Authority of Survey': 'مصری جنرل اتھارٹی آف سروے',
      'Gulf Region': 'خلیجی خطہ',
      'Kuwait': 'کویت',
      'Qatar': 'قطر',
      'Majlis Ugama Islam Singapura, Singapore': 'مجلس علماء اسلام سنگاپور',
      'Standard (Shafi\'i, Maliki, Hanbali)': 'معیاری (شافعی، مالکی، حنبلی)',
      'Hanafi': 'حنفی',
      'Dua copied': 'دعا کاپی ہوگئی',
      'Link copied': 'لنک کاپی ہوگیا',
      'Copy': 'کاپی',
      'Share': 'شیئر',
      'Location Settings': 'مقام کی ترتیبات',
      'Auto Detect Location': 'مقام خود بخود تلاش کریں',
      'Area': 'علاقہ',
      'City': 'شہر',
      'State': 'صوبہ',
      'Country': 'ملک',
      'Pincode': 'پن کوڈ',
      'Save': 'محفوظ کریں',
      'Could not obtain GPS location': 'GPS مقام حاصل نہیں ہوسکا',
      'Please enter city and country': 'براہ کرم شہر اور ملک درج کریں',
      'Lifetime Progress': 'زندگی بھر کی پیشرفت',
      'BEADS': 'تسبیح کے دانے',
      'End - ': 'ختم - ',
      'End': 'ختم',
      'Prayer Times & Qibla Direction app.': 'نماز کے اوقات اور قبلہ رخ معلوم کرنے کی ایپ۔',
      'Developer Details': 'ڈیولپر کی تفصیلات',
      'Name': 'نام',
      'Email': 'ای میل',
      'Phone': 'فون',
      'UPCOMING SALAH': 'اگلی نماز',
      'Upcoming': 'اگلا',
      'Next Salah Begins In': 'اگلی نماز شروع ہونے میں',
      'Monday': 'پیر',
      'Tuesday': 'منگل',
      'Wednesday': 'بدھ',
      'Thursday': 'جمعرات',
      'Friday': 'جمعہ',
      'Saturday': 'ہفتہ',
      'Sunday': 'اتوار',
      'Mon': 'پیر',
      'Tue': 'منگل',
      'Wed': 'بدھ',
      'Thu': 'جمعرات',
      'Fri': 'جمعہ',
      'Sat': 'ہفتہ',
      'Sun': 'اتوار',
      'Muharram': 'محرم',
      'Safar': 'صفر',
      'Rabi\' al-awwal': 'ربیع الاول',
      'Rabi\' al-thani': 'ربیع الثانی',
      'Jumada al-ula': 'جمادی الاول',
      'Jumada al-akhira': 'جمادی الثانی',
      'Rajab': 'رجب',
      'Sha\'ban': 'شعبان',
      'Ramadan': 'رمضان',
      'Shawwal': 'شوال',
      'Dhu al-Qi\'dah': 'ذوالقعدہ',
      'Dhu al-Hijjah': 'ذوالحجہ',
      'View both English and Hijri dates easily for the whole month.':
          'پورے مہینے کی انگریزی اور ہجری تاریخیں آسانی سے دیکھیں۔',
      'Our Lord, give us in this world [that which is] good and in the Hereafter [that which is] good and protect us from the punishment of the Fire.':
          'اے ہمارے رب، ہمیں دنیا میں بھی بھلائی عطا فرما اور آخرت میں بھی بھلائی عطا فرما اور ہمیں آگ کے عذاب سے بچا۔',
      'He who does not show mercy to others, Allah will not show mercy to him.':
          'جو دوسروں پر رحم نہیں کرتا، اللہ بھی اس پر رحم نہیں فرماتا۔',
      'Ayatul Kursi': 'آیت الکرسی',
      'Allah - there is no deity except Him, the Ever-Living, the Sustainer of [all] existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is [presently] before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His Kursi extends over the heavens and the earth, and their preservation tires Him not. And He is the Most High, the Most Great.':
          'اللہ، اس کے سوا کوئی معبود نہیں، وہ زندہ ہے، سب کا تھامنے والا ہے۔ نہ اسے اونگھ آتی ہے نہ نیند۔ اسی کا ہے جو کچھ آسمانوں میں ہے اور جو کچھ زمین میں ہے۔ کون ہے جو اس کے پاس اس کی اجازت کے بغیر سفارش کر سکے۔ وہ جانتا ہے جو ان کے سامنے ہے اور جو ان کے پیچھے ہے۔ اور وہ اس کے علم میں سے کسی چیز کا احاطہ نہیں کر سکتے مگر جتنا وہ چاہے ۔ اس کی کرسی آسمانوں اور زمین پر چھائی ہوئی ہے اور ان کی حفاظت اسے تھکاتی نہیں ہے اور وہ بہت بلند و بالا، بہت بڑا ہے۔',
      'Say, "He is Allah, [who is] One, Allah, the Eternal Refuge. He neither begets nor is born, Nor is there to Him any equivalent."':
          'کہہ دو کہ وہ اللہ ایک ہے۔ اللہ بے نیاز ہے۔ نہ اس نے کسی کو جنا اور نہ وہ جنا گیا۔ اور اس کا کوئی ہمسر نہیں۔',
      'Say, "I seek refuge in the Lord of daybreak From the evil of that which He created And from the evil of darkness when it settles And from the evil of the blowers in knots And from the evil of an envier when he envies."':
          'کہو: میں صبح کے رب کی پناہ مانگتا ہوں۔ اس کی شر سے جو اس نے پیدا کی۔ اور اندھیری رات کی شر سے جب وہ چھا جائے۔ اور گرہوں میں پھونکنے والیوں کی شر سے۔ اور حسد کرنے والے کی شر سے جب وہ حسد کرے۔',
      'Say, "I seek refuge in the Lord of mankind, The Sovereign of mankind, The God of mankind, From the evil of the retreating whisperer - Who whispers [evil] into the breasts of mankind - From among the jinn and mankind."':
          'کہو: میں لوگوں کے رب کی پناہ مانگتا ہوں۔ لوگوں کے بادشاہ کی، لوگوں کے معبود کی۔ وسوسہ ڈالنے والے، پیچھے ہٹ جانے والے کی شر سے۔ جو لوگوں کے سینوں میں وسوسہ ڈالتا ہے۔ خواہ وہ جنوں میں سے ہو یا انسانوں میں سے۔',
      'Say, "O disbelievers, I do not worship what you worship. Nor are you worshippers of what I worship. Nor will I be a worshipper of what you have worshipped. Nor will you be worshippers of what I worship. For you is your religion, and for me is my religion."':
          'کہو: اے کافروں! میں ان کی عبادت نہیں کرتا جن کی تم عبادت کرتے ہو۔ اور نہ تم اس کی عبادت کرنے والے ہو جس کی میں عبادت کرتا ہوں۔ اور نہ میں ان کی عبادت کرنے والا ہوں جن کی تم نے عبادت کی۔ اور نہ تم اس کی عبادت کرنے والے ہو جس کی میں عبادت کرتا ہوں۔ تمہارے لیے تمہارا دین ہے اور میرے لیے میرا دین۔',
      'In the name of Allah, the Entirely Merciful, the Especially Merciful. [All] praise is [due] to Allah, Lord of the worlds - The Entirely Merciful, the Especially Merciful, Sovereign of the Day of Recompense. It is You we worship and You we ask for help. Guide us to the straight path - The path of those upon whom You have bestowed favor, not of those who have evoked [Your] anger or of those who are astray.':
          'اللہ کے نام سے جو نہایت مہربان، ہمیشہ رحم فرمانے والا ہے۔ تمام تعریفیں اللہ ہی کے لیے ہیں جو تمام جہانوں کا رب ہے۔ نہایت مہربان، ہمیشہ رحم فرمانے والا ہے۔ روزِ جزاء کا مالک ہے۔ ہم تیری ہی عبادت کرتے ہیں اور تجھ ہی سے مدد مانگتے ہیں۔ ہمیں سیدھے راستے پر چلا۔ ان لوگوں کے راستے پر جن پر تو نے انعام فرمایا، نہ ان کے راستے پر جن پر غضب کیا گیا اور نہ گمراہوں کے۔',
      'My Lord, increase me in knowledge.': 'اے میرے رب، میرے علم میں اضافہ فرما۔',
      'My Lord, have mercy upon them as they brought me up [when I was] small.':
          'اے میرے رب، ان دونوں پر رحم فرما جیسا کہ انہوں نے بچپن میں میری پرورش کی۔',
      'Detected:': 'تلاش کیا گیا:',
      'Qibla Direction': 'قبلہ کی سمت',
      'Qibla Angle': 'قبلہ کا زاویہ',
      'Distance': 'فاصلہ',
      'Align the needle to the top of the compass to face the Qibla directly.':
          'قبلہ کی صحیح سمت جاننے کے لیے سوئی کو قطب نما کے اوپر والے حصے سے ملائیں۔',
      '2 Rakats Sunnah (Muakkadah)\n2 Rakats Fard\nTotal: 4 Rakats':
          '2 رکعت سنت (موکدہ)\n2 رکعت فرض\nکل: 4 رکعت',
      '4 Rakats Sunnah (Muakkadah)\n4 Rakats Fard\n2 Rakats Sunnah (Muakkadah)\n2 Rakats Nafl\nTotal: 12 Rakats':
          '4 رکعت سنت (موکدہ)\n4 رکعت فرض\n2 رکعت سنت (موکدہ)\n2 رکعت نفل\nکل: 12 رکعت',
      '4 Rakats Sunnah (Ghair Muakkadah)\n4 Rakats Fard\nTotal: 8 Rakats':
          '4 رکعت سنت (غیر موکدہ)\n4 رکعت فرض\nکل: 8 رکعت',
      '3 Rakats Fard\n2 Rakats Sunnah (Muakkadah)\n2 Rakats Nafl\nTotal: 7 Rakats':
          '3 رکعت فرض\n2 رکعت سنت (موکدہ)\n2 رکعت نفل\nکل: 7 رکعت',
      '4 Rakats Sunnah (Ghair Muakkadah)\n4 Rakats Fard\n2 Rakats Sunnah (Muakkadah)\n2 Rakats Nafl\n3 Rakats Witr\n2 Rakats Nafl\nTotal: 17 Rakats':
          '4 رکعت سنت (غیر موکدہ)\n4 رکعت فرض\n2 رکعت سنت (موکدہ)\n2 رکعت نفل\n3 رکعت وتر\n2 رکعت نفل\nکل: 17 رکعت',
      '4 Rakats Sunnah (Muakkadah)\n2 Rakats Fard\n4 Rakats Sunnah (Muakkadah)\n2 Rakats Sunnah (Muakkadah)\n2 Rakats Nafl\nTotal: 14 Rakats':
          '4 رکعت سنت (موکدہ)\n2 رکعت فرض\n4 رکعت سنت (موکدہ)\n2 رکعت سنت (موکدہ)\n2 رکعت نفل\nکل: 14 رکعت',
      'Step 1: Durood Shareef': 'پہلا قدم: درود شریف',
      'Read Durood Shareef 3, 5, 7, or 11 times. (e.g., Durood-e-Ibrahimi)':
          'درود شریف 3، 5، 7، یا 11 بار پڑھیں۔ (مثلاً درودِ ابراہیمی)',
      'Step 2: Surah Al-Kafirun (1 time)': 'دوسرا قدم: سورہ الکافرون (1 بار)',
      'Read Surah Al-Kafirun 1 time.': 'سورہ الکافرون 1 بار پڑھیں۔',
      'Step 3: Surah Al-Ikhlas (3 times)': 'تیسرا قدم: سورہ الاخلاص (3 بار)',
      'Read Surah Al-Ikhlas (Qul Huwa Allahu Ahad) 3 times.':
          'سورہ الاخلاص (قل ھو اللہ احد) 3 بار پڑھیں۔',
      'Step 4: Surah Al-Falaq (1 time)': 'چوتھا قدم: سورہ الفلق (1 بار)',
      'Read Surah Al-Falaq 1 time.': 'سورہ الفلق 1 بار پڑھیں۔',
      'Step 5: Surah An-Nas (1 time)': 'پانچواں قدم: سورہ الناس (1 بار)',
      'Read Surah An-Nas 1 time.': 'سورہ الناس 1 بار پڑھیں۔',
      'Step 6: Surah Al-Fatiha (1 time)': 'چھٹا قدم: سورہ فاتحہ (1 بار)',
      'Read Surah Al-Fatiha (Alhamdulillah) 1 time.': 'سورہ فاتحہ (الحمد للہ) 1 بار پڑھیں۔',
      'Step 7: Surah Al-Baqarah (Beginning)': 'ساتواں قدم: سورہ بقرہ (شروع)',
      'Read the first 5 Ayats of Surah Al-Baqarah.': 'سورہ بقرہ کی پہلی 5 آیات پڑھیں۔',
      'Step 8: Final Durood and Dua': 'آٹھواں قدم: آخری درود اور دعا',
      'Recite Durood Shareef again 3, 5, 7 or 11 times. Then raise your hands in Dua and ask Allah to accept it and present the reward (Esaal-e-Sawab) to the beloved Prophet (PBUH), his family, companions, all Awliya Allah, and all deceased Muslims.':
          'درود شریف دوبارہ 3، 5، 7 یا 11 بار پڑھیں۔ پھر ہاتھ اٹھا کر دعا مانگیں کہ اللہ تعالیٰ اسے قبول فرمائے اور اس کا ثواب (ایصالِ ثواب) پیارے نبی صلی اللہ علیہ وسلم، ان کی آل، اصحاب، تمام اولیاء اللہ اور تمام مرحوم مسلمانوں تک پہنچائے۔',
      'Arabi (عربی)': 'عربی',
      'Hindi (हिंदी)': 'ہندی',
    },
    'hi': {
      'Timetable': 'समय-सारणी',
      'Ramzan': 'रमजान',
      'Qibla': 'किबला',
      'Dua': 'दुआ',
      'Tasbih': 'तस्बीह',
      'Salatuk Options': 'सलातुक विकल्प',
      'Settings': 'सेटिंग्स',
      'Namaz Tarika': 'नमाज़ का तरीका',
      'Fatiha Ka Tarika': 'फ़ातिहा का तरीका',
      'Calendar': 'कैलेंडर',
      'About App': 'ऐप के बारे में',
      'Appearance': 'दिखावट',
      'Dark Mode': 'डार्क मोड',
      'Alarm & Times': 'अलार्म और समय',
      'Ring Adhan time': 'अज़ान के समय बजाएं',
      'Set Manual Prayer Times': 'मैनुअल प्रार्थना समय निर्धारित करें',
      'Prayer Notifications': 'प्रार्थना सूचनाएं',
      'Location updated': 'स्थान अपडेट किया गया',
      'Advanced Prayer Calculation': 'उन्नत नमाज़ गणना',
      'Calculation Method': 'गणना का तरीका',
      'Asr Method (Juristic)': 'असर का तरीका',
      'Hijri Date Adjustment': 'हिजरी तिथि समायोजन',
      '-2 Days': '-2 दिन',
      '-1 Day': '-1 दिन',
      '0 Days (No offset)': '0 दिन (कोई बदलाव नहीं)',
      '+1 Day': '+1 दिन',
      '+2 Days': '+2 दिन',
      'Not Set': 'सेट नहीं है',
      'Location: ': 'स्थान: ',
      'Fajr': 'फ़ज्र',
      'Sunrise': 'सूर्योदय',
      'Sunset': 'सूर्यास्त',
      'Dhuhr': 'ज़ुहर',
      'Asr': 'असर',
      'Maghrib': 'मग़रिब',
      'Isha': 'ईशा',
      'Jummah': 'जुम्मा',
      'Jumah': 'जुम्मा',
      'Sehr': 'सहर',
      'Iftar': 'इफ्तार',
      'Next Prayer': 'अगली नमाज़',
      'Manual Mode': 'मैनुअल मोड',
      'Hijri': 'हिजरी',
      'Reset': 'रीसेट',
      'Count': 'गिनती',
      'Total Count': 'कुल गिनती',
      'Daily Count': 'आज की गिनती',
      'Minus': 'घटाएं',
      'Home': 'होम',
      'Prayer': 'नमाज़',
      'Daily Ayah': 'आज की आयत',
      'Daily Dua': 'आज की दुआ',
      'Daily Hadith': 'आज की हदीस',
      '👉 Welcome to Salatuk Timetable • Daily Salah & Ramzan Updates • Please keep your phone on silent 📵 during Jamaat • 🤲 Pray on time to be successful in both worlds • May Allah 🕋 accept our prayers • JazakAllah Khair':
          '👉 सलातुक समय-सारणी में आपका स्वागत है • दैनिक नमाज़ और रमज़ान अपडेट • कृपया जमात के दौरान अपना फ़ोन साइलेंट 📵 मोड पर रखें • 🤲 दोनों जहानों में सफलता के लिए समय पर नमाज़ पढ़ें • अल्लाह 🕋 हमारी दुआएँ स्वीकार करे • जज़ाकल्लाह खैर',
      'Error loading times': 'समय लोड करने में त्रुटि',
      'Ramzan Timetable': 'रमजान समय-सारणी',
      'SEHR': 'सहर',
      'IFTAR': 'इफ्तार',
      'COUNT': 'गिनती',
      'Rakats Details:': 'रकात विवरण:',
      'Urdu Niyyat (نیت):': 'उर्दू नीयत (نیت):',
      'Hindi Niyyat (नीयत):': 'हिंदी नीयत (नीयत):',
      'PRAYER': 'नमाज़',
      'AZAN': 'अज़ान',
      'JAMAAT': 'जमात',
      'ENDS': 'अंत',
      'English': 'अंग्रेजी',
      'Reset Total Count?': 'कुल गिनती रीसेट करें?',
      'Reset Total Count': 'कुल गिनती रीसेट करें',
      'Are you sure you want to reset your lifetime tasbih progress?':
          'क्या आप वाकई अपनी जीवन भर की तस्बीह प्रोग्रेस को रीसेट करना चाहते हैं?',
      'Cancel': 'रद्द करें',
      'SubhanAllah': 'सुभानअल्लाह',
      'Alhamdulillah': 'अल्हम्दुलिल्लाह',
      'Allahu Akbar': 'अल्लाहु अकबर',
      'Master Sound Toggle': 'मास्टर साउंड',
      'Enable or disable all Azan/Jamat sounds': 'सभी अज़ान और जमात की आवाज़ें चालू या बंद करें',
      'Show/Hide individual prayer settings': 'प्रार्थना सेटिंग्स दिखाएं या छिपाएं',
      'Azan & Jamaat Time': 'अज़ान और जमात का समय',
      'Override default times': 'डिफ़ॉल्ट समय बदलें',
      'Prayer Calculation': 'नमाज़ की गणना',
      'Show advanced settings': 'एडवांस्ड सेटिंग्स दिखाएं',
      'University of Islamic Sciences, Karachi': 'इस्लामिक विज्ञान विश्वविद्यालय, कराची',
      'Islamic Society of North America (ISNA)': 'इस्लामिक सोसाइटी ऑफ नॉर्थ अमेरिका (ISNA)',
      'Muslim World League': 'मुस्लिम वर्ल्ड लीग',
      'Umm Al-Qura University, Makkah': 'उम्म अल-कुरा विश्वविद्यालय, मक्का',
      'Egyptian General Authority of Survey': 'मिस्र के जनरल अथॉरिटी ऑफ सर्वे',
      'Gulf Region': 'खाड़ी क्षेत्र',
      'Kuwait': 'कुवैत',
      'Qatar': 'कतर',
      'Majlis Ugama Islam Singapura, Singapore': 'मजलिस उगामा इस्लाम सिंगापुरा',
      'Standard (Shafi\'i, Maliki, Hanbali)': 'मानक (शाफ़ेई, मलिकी, हनबली)',
      'Hanafi': 'हनफी',
      'Dua copied': 'दुआ कॉपी हो गई',
      'Link copied': 'लिंक कॉपी हो गया',
      'Copy': 'कॉपी',
      'Share': 'शेयर',
      'Location Settings': 'स्थान सेटिंग्स',
      'Auto Detect Location': 'ऑटो स्थान का पता लगाएं',
      'Area': 'क्षेत्र',
      'City': 'शहर',
      'State': 'राज्य',
      'Country': 'देश',
      'Pincode': 'पिनकोड',
      'Save': 'सहेजें',
      'Could not obtain GPS location': 'GPS स्थान प्राप्त नहीं किया जा सका',
      'Please enter city and country': 'कृपया शहर और देश दर्ज करें',
      'Lifetime Progress': 'कुल प्रोग्रेस',
      'BEADS': 'तस्बीह',
      'End - ': 'समाप्त - ',
      'End': 'अंत',
      'Prayer Times & Qibla Direction app.': 'नमाज़ के समय और क़िबला दिशा बताने वाला ऐप।',
      'Developer Details': 'डेवलपर विवरण',
      'Name': 'नाम',
      'Email': 'ईमेल',
      'Phone': 'फोन',
      'UPCOMING SALAH': 'अगली नमाज़',
      'Upcoming': 'अगला',
      'Next Salah Begins In': 'अगली नमाज़ शुरू होने में',
      'Monday': 'सोमवार',
      'Tuesday': 'मंगलवार',
      'Wednesday': 'बुधवार',
      'Thursday': 'गुरुवार',
      'Friday': 'शुक्रवार',
      'Saturday': 'शनिवार',
      'Sunday': 'रविवार',
      'Mon': 'सोम',
      'Tue': 'मंगल',
      'Wed': 'बुध',
      'Thu': 'गुरु',
      'Fri': 'शुक्र',
      'Sat': 'शनि',
      'Sun': 'रवि',
      'Muharram': 'मुहर्रम',
      'Safar': 'सफ़र',
      'Rabi\' al-awwal': 'रबी-अल-अव्वल',
      'Rabi\' al-thani': 'रबी-अल-थानी',
      'Jumada al-ula': 'जमादा-अल-औला',
      'Jumada al-akhira': 'जमादा-अल-आखिरा',
      'Rajab': 'रजब',
      'Sha\'ban': 'शाबान',
      'Ramadan': 'रमजान',
      'Shawwal': 'शव्वाल',
      'Dhu al-Qi\'dah': 'ज़िलक़ादा',
      'Dhu al-Hijjah': 'ज़िलहिज्जा',
      'View both English and Hijri dates easily for the whole month.':
          'पूरे महीने की अंग्रेजी और हिजरी तारीखें आसानी से देखें।',
      'Our Lord, give us in this world [that which is] good and in the Hereafter [that which is] good and protect us from the punishment of the Fire.':
          'हे हमारे रब, हमें दुनिया में भी अच्छाई दे और आखिरत में भी अच्छाई दे और हमें आग के अज़ाब से बचा।',
      'He who does not show mercy to others, Allah will not show mercy to him.':
          'जो दूसरों पर रहम नहीं करता, अल्लाह भी उस पर रहम नहीं करता।',
      'Ayatul Kursi': 'आयतुल कुर्सी',
      'Allah - there is no deity except Him, the Ever-Living, the Sustainer of [all] existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is [presently] before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His Kursi extends over the heavens and the earth, and their preservation tires Him not. And He is the Most High, the Most Great.':
          'अल्लाह, उसके सिवा कोई पूजा के योग्य नहीं, वह जीवित है, सबका थामने वाला है। न उसे ऊँघ आती है न नींद। उसी का है जो कुछ आसमानों में है और जो कुछ ज़मीन में है। कौन है जो उसके पास उसकी अनुमति के बिना सिफारिश कर सके? वह जानता है जो उनके सामने है और जो उनके पीछे है। और वे उसके ज्ञान में से किसी चीज़ का घेराव नहीं कर सकते मगर जितना वह चाहे। उसकी कुर्सी आसमानों और ज़मीन पर छाई हुई है और उनकी रक्षा उसे थकाती नहीं है और वह बहुत ऊँचा और बहुत बड़ा है।',
      'Say, "He is Allah, [who is] One, Allah, the Eternal Refuge. He neither begets nor is born, Nor is there to Him any equivalent."':
          'कहो, वह अल्लाह एक है। अल्लाह बेनियाज़ है। न उससे कोई पैदा हुआ और न वह किसी से पैदा हुआ। और उसका कोई समकक्ष नहीं है।',
      'Say, "I seek refuge in the Lord of daybreak From the evil of that which He created And from the evil of darkness when it settles And from the evil of the blowers in knots And from the evil of an envier when he envies."':
          'कहो, मैं शरण लेता हूँ सुबह के रब की। उसकी बुराई से जो उसने पैदा किया। और अंधेरी रात की बुराई से जब वह छा जाए। और गिरहों में फूँकने वालियों (जादूगरों) की बुराई से। और ईर्ष्या करने वाले की बुराई से जब वह ईर्ष्या करे।',
      'Say, "I seek refuge in the Lord of mankind, The Sovereign of mankind, The God of mankind, From the evil of the retreating whisperer - Who whispers [evil] into the breasts of mankind - From among the jinn and mankind."':
          'कहो, मैं शरण लेता हूँ इंसानों के रब की। इंसानों के बादशाह की। इंसानों के खुदा की। उस वसवसा डालने वाले (शैतान) की बुराई से जो पीछे हट जाता है। जो लोगों के दिलों में वसवसा डालता है। चाहे वह जिन्न में से हो या इंसानों में से।',
      'Say, "O disbelievers, I do not worship what you worship. Nor are you worshippers of what I worship. Nor will I be a worshipper of what you have worshipped. Nor will you be worshippers of what I worship. For you is your religion, and for me is my religion."':
          'कहो, ऐ काफिरों! मैं उनकी इबादत नहीं करता जिनकी तुम इबादत करते हो। और न तुम उसकी इबादत करने वाले हो जिसकी मैं इबादत करता हूँ। और न मैं उनकी इबादत करने वाला हूँ जिनकी तुमने इबादत की। और न तुम उसकी इबादत करने वाले हो जिसकी मैं इबादत करता हूँ। तुम्हारे लिए तुम्हारा धर्म और मेरे लिए मेरा धर्म।',
      'In the name of Allah, the Entirely Merciful, the Especially Merciful. [All] praise is [due] to Allah, Lord of the worlds - The Entirely Merciful, the Especially Merciful, Sovereign of the Day of Recompense. It is You we worship and You we ask for help. Guide us to the straight path - The path of those upon whom You have bestowed favor, not of those who have evoked [Your] anger or of those who are astray.':
          'अल्लाह के नाम से जो अत्यंत दयालु और अत्यंत कृपाशील है। [सभी] प्रशंसा अल्लाह के लिए है, जो दुनिया के रब हैं - अत्यंत दयालु, अत्यंत कृपाशील, पुरस्कार के दिन के स्वामी। हम तेरी ही इबादत करते हैं और तुझी से मदद माँगते हैं। हमें सीधे रास्ते पर ले चल - उन लोगों का रास्ता जिन पर तूने उपकार किया है, उनका नहीं जिन पर [तेरा] क्रोध हुआ और न ही उनका जो भटक गए हैं।',
      'My Lord, increase me in knowledge.': 'ऐ मेरे रब, मेरे ज्ञान में वृद्धि कर।',
      'My Lord, have mercy upon them as they brought me up [when I was] small.':
          'ऐ मेरे रब, उन पर दया कर जैसा कि उन्होंने बचपन में मेरा पालन-पोषण किया।',
      'Detected:': 'पता चला:',
      'Qibla Direction': 'क़िबला दिशा',
      'Qibla Angle': 'क़िबला कोण',
      'Distance': 'दूरी',
      'Align the needle to the top of the compass to face the Qibla directly.':
          'क़िबला की सही दिशा जानने के लिए सुई को कंपास के ऊपरी हिस्से से संरेखित करें।',
      '2 Rakats Sunnah (Muakkadah)\n2 Rakats Fard\nTotal: 4 Rakats':
          '2 रकात सुन्नत (मुअक्कदह)\n2 रकात फ़र्ज़\nकुल: 4 रकात',
      '4 Rakats Sunnah (Muakkadah)\n4 Rakats Fard\n2 Rakats Sunnah (Muakkadah)\n2 Rakats Nafl\nTotal: 12 Rakats':
          '4 रकात सुन्नत (मुअक्कदह)\n4 रकात फ़र्ज़\n2 रकात सुन्नत (मुअक्कदह)\n2 रकात नफ़्ल\nकुल: 12 रकात',
      '4 Rakats Sunnah (Ghair Muakkadah)\n4 Rakats Fard\nTotal: 8 Rakats':
          '4 रकात सुन्नत (ग़ैर मुअक्कदह)\n4 रकात फ़र्ज़\nकुल: 8 रकात',
      '3 Rakats Fard\n2 Rakats Sunnah (Muakkadah)\n2 Rakats Nafl\nTotal: 7 Rakats':
          '3 रकात फ़र्ज़\n2 रकात सुन्नत (मुअक्कदह)\n2 रकात नफ़्ल\nकुल: 7 रकात',
      '4 Rakats Sunnah (Ghair Muakkadah)\n4 Rakats Fard\n2 Rakats Sunnah (Muakkadah)\n2 Rakats Nafl\n3 Rakats Witr\n2 Rakats Nafl\nTotal: 17 Rakats':
          '4 रकात सुन्नत (ग़ैर मुअक्कदह)\n4 रकात फ़र्ज़\n2 रकात सुन्नत (मुअक्कदह)\n2 रकात नफ़्ल\n3 रकात वित्र\n2 रकात नफ़्ल\nकुल: 17 रकात',
      '4 Rakats Sunnah (Muakkadah)\n2 Rakats Fard\n4 Rakats Sunnah (Muakkadah)\n2 Rakats Sunnah (Muakkadah)\n2 Rakats Nafl\nTotal: 14 Rakats':
          '4 रकात सुन्नत (मुअक्कदह)\n2 रकात फ़र्ज़\n4 रकात सुन्नत (मुअक्कदह)\n2 रकात सुन्नत (मुअक्कदह)\n2 रकात नफ़्ल\nकुल: 14 रकात',
      'Step 1: Durood Shareef': 'चरण 1: दरूद शरीफ',
      'Read Durood Shareef 3, 5, 7, or 11 times. (e.g., Durood-e-Ibrahimi)':
          'दरूद शरीफ 3, 5, 7, या 11 बार पढ़ें। (जैसे दरूद-ए-इब्राहिमी)',
      'Step 2: Surah Al-Kafirun (1 time)': 'चरण 2: सूरह अल-काफिरून (1 बार)',
      'Read Surah Al-Kafirun 1 time.': 'सूरह अल-काफिरून 1 बार पढ़ें।',
      'Step 3: Surah Al-Ikhlas (3 times)': 'चरण 3: सूरह अल-इखलास (3 बार)',
      'Read Surah Al-Ikhlas (Qul Huwa Allahu Ahad) 3 times.':
          'सूरह अल-इखलास (कुल हु अल्लाहु अहद) 3 बार पढ़ें।',
      'Step 4: Surah Al-Falaq (1 time)': 'चरण 4: सूरह अल-फलक (1 बार)',
      'Read Surah Al-Falaq 1 time.': 'चरण 4: सूरह अल-फलक 1 बार पढ़ें।',
      'Step 5: Surah An-Nas (1 time)': 'चरण 5: सूरह अन-नास (1 बार)',
      'Read Surah An-Nas 1 time.': 'चरण 5: सूरह अन-नास 1 बार पढ़ें।',
      'Step 6: Surah Al-Fatiha (1 time)': 'चरण 6: सूरह अल-फ़ातिहा (1 बार)',
      'Read Surah Al-Fatiha (Alhamdulillah) 1 time.':
          'सूरह अल-फ़ातिहा (अलहम्दुलिल्लाह) 1 बार पढ़ें।',
      'Step 7: Surah Al-Baqarah (Beginning)': 'चरण 7: सूरह अल-बक़रह (शुरुआत)',
      'Read the first 5 Ayats of Surah Al-Baqarah.': 'सूरह अल-बक़रह की पहली 5 आयतें पढ़ें।',
      'Step 8: Final Durood and Dua': 'चरण 8: अंतिम दरूद और दुआ',
      'Recite Durood Shareef again 3, 5, 7 or 11 times. Then raise your hands in Dua and ask Allah to accept it and present the reward (Esaal-e-Sawab) to the beloved Prophet (PBUH), his family, companions, all Awliya Allah, and all deceased Muslims.':
          'दरूद शरीफ दोबारा 3, 5, 7 या 11 बार पढ़ें। फिर दुआ के लिए हाथ उठाएं और अल्लाह से इसे स्वीकार करने और इसका सवाब (ईसाल-ए-सवाब) प्यारे नबी (स.अ.व.), उनके परिवार, साथियों, सभी औलिया अल्लाह और सभी मरहूम मुसलमानों को पहुँचाने की दुआ करें।',
      'Arabi (عربی)': 'अरबी',
      'Hindi (हिंदी)': 'हिंदी',
    },
  };
}
