import 'package:get/get.dart';
// Export everything from GetX so that it's available globally via localization_service.dart
export 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      'Timetable': 'Timetable',
      'Ramzan': 'Ramzan',
      'Qibla': 'Qibla',
      'Dua': 'Dua',
      'Tasbih': 'Tasbih',
      'Salatuk Options': 'Salatuk Options',
      'Settings': 'Settings',
      'Namaz Tarika': 'Namaz Tarika',
      'Fatiha Ka Tarika': 'Fatiha Ka Tarika',
      'Calendar': 'Calendar',
      'About App': 'About App',
      'Appearance': 'Appearance',
      'Dark Mode': 'Dark Mode',
      'Alarm & Times': 'Alarm & Times',
      'Ring Adhan time': 'Ring Adhan time',
      'Set Manual Prayer Times': 'Set Manual Prayer Times',
      'Prayer Notifications': 'Prayer Notifications',
      'Location updated': 'Location updated',
      'Advanced Prayer Calculation': 'Advanced Prayer Calculation',
      'Calculation Method': 'Calculation Method',
      'Asr Method (Juristic)': 'Asr Method (Juristic)',
      'Hijri Date Adjustment': 'Hijri Date Adjustment',
      '-2 Days': '-2 Days',
      '-1 Day': '-1 Day',
      '0 Days (No offset)': '0 Days (No offset)',
      '+1 Day': '+1 Day',
      '+2 Days': '+2 Days',
      'Not Set': 'Not Set',
      'Location: ': 'Location: ',
      'Fajr': 'Fajr',
      'Sunrise': 'Sunrise',
      'Sunset': 'Sunset',
      'Dhuhr': 'Dhuhr',
      'Asr': 'Asr',
      'Maghrib': 'Maghrib',
      'Isha': 'Isha',
      'Jummah': 'Jummah',
      'Jumah': 'Jummah',
      'Sehr': 'Sehr',
      'Iftar': 'Iftar',
      'Next Prayer': 'Next Prayer',
      'Manual Mode': 'Manual Mode',
      'Hijri': 'Hijri',
      'Reset': 'Reset',
      'Count': 'Count',
      'Total Count': 'Total Count',
      'Daily Count': 'Daily Count',
      'Minus': 'Minus',
      'Ramzan Timetable': 'Ramzan Timetable',
      'SEHR': 'SEHR',
      'IFTAR': 'IFTAR',
      'Rakats Details:': 'Rakats Details:',
      'Urdu Niyyat (نیت):': 'Urdu Niyyat (نیت):',
      'Hindi Niyyat (नीयत):': 'Hindi Niyyat (नीयत):',
      'PRAYER': 'PRAYER',
      'AZAN': 'AZAN',
      'JAMAAT': 'JAMAAT',
      'ENDS': 'ENDS',
      'English': 'English',
      'Reset Total Count?': 'Reset Total Count?',
      'Are you sure you want to reset your lifetime tasbih progress?':
          'Are you sure you want to reset your lifetime tasbih progress?',
      'Cancel': 'Cancel',
      'Prayer Azan & Jamaat Time': 'Prayer Azan & Jamaat Time',
      'Override default API times': 'Override default API times',
      'Prayer Override': 'Prayer Override',
      'Azan Time': 'Azan Time',
      'Jamaat Time': 'Jamaat Time',
      'API Default': 'API Default',
      'Reset to Default?': 'Reset to Default?',
      'This will clear all manual times and use API defaults.':
          'This will clear all manual times and use API defaults.',
      'Success': 'Success',
      'All times reset to default': 'All times reset to default',
      'Fajr End': 'Fajr End',
      'Dhuhr End': 'Dhuhr End',
      'Asr End': 'Asr End',
      'Maghrib End': 'Maghrib End',
      'Isha End': 'Isha End',
    },
    'ur': {
      'Timetable': 'ٹائم ٹیبل',
      'Ramzan': 'رمضان',
      'Qibla': 'قبلہ',
      'Dua': 'دعا',
      'Tasbih': 'تسبیح',
      'Salatuk Options': 'صلاتک کے اختیارات',
      'Settings': 'ترتیبات',
      'Namaz Tarika': 'نماز کا طریقہ',
      'Fatiha Ka Tarika': 'فاتحہ کا طریقہ',
      'Calendar': 'تقویم (کیلنڈر)',
      'About App': 'ایپ کے بارے میں',
      'Appearance': 'ظاہری شکل',
      'Dark Mode': 'ڈارک موڈ',
      'Alarm & Times': 'الارم اور اوقات',
      'Ring Adhan time': 'اذان کے وقت بجائیں',
      'Set Manual Prayer Times': 'دستی نماز کے اوقات متعین کریں',
      'Prayer Notifications': 'نماز کی اطلاعات',
      'Location updated': 'مقام اپ ڈیٹ ہو گیا',
      'Advanced Prayer Calculation': 'نماز کا تفصیلی حساب',
      'Calculation Method': 'حساب کا طریقہ',
      'Asr Method (Juristic)': 'عصر کا طریقہ (فقہی)',
      'Hijri Date Adjustment': 'ہجری تاریخ کی ترتیب',
      '-2 Days': '-2 دن',
      '-1 Day': '-1 دن',
      '0 Days (No offset)': '0 دن (کوئی تبدیلی نہیں)',
      '+1 Day': '+1 دن',
      '+2 Days': '+2 دن',
      'Not Set': 'طے نہیں کیا',
      'Location: ': 'مقام: ',
      'Fajr': 'فجر',
      'Sunrise': 'طلوع آفتاب',
      'Sunset': 'غروب آفتاب',
      'Dhuhr': 'ظہر',
      'Asr': 'عصر',
      'Maghrib': 'مغرب',
      'Isha': 'عشاء',
      'Jummah': 'جمعہ',
      'Jumah': 'جمعہ',
      'Sehr': 'سحر',
      'Iftar': 'افطار',
      'Next Prayer': 'اگلی نماز',
      'Manual Mode': 'دستی موڈ',
      'Hijri': 'ہجری',
      'Reset': 'ری سیٹ',
      'Count': 'گنتی',
      'Total Count': 'کل گنتی',
      'Daily Count': 'آج کی گنتی',
      'Minus': 'کم کریں',
      'Ramzan Timetable': 'رمضان ٹائم ٹیبل',
      'SEHR': 'سحر',
      'IFTAR': 'افطار',
      'Rakats Details:': 'رکعت کی تفصیلات:',
      'Urdu Niyyat (نیت):': 'اردو نیت:',
      'Hindi Niyyat (नीयت):': 'ہندی نیت:',
      'PRAYER': 'نماز',
      'AZAN': 'اذان',
      'JAMAAT': 'جماعت',
      'ENDS': 'ختم',
      'English': 'انگریزی',
      'Reset Total Count?': 'کل گنتی ری سیٹ کریں؟',
      'Are you sure you want to reset your lifetime tasbih progress?':
          'کیا آپ واقعی اپنی زندگی بھر کی تسبیح کی پیشرفت کو ری سیٹ کرنا چاہتے ہیں؟',
      'Cancel': 'منسوخ کریں',
    },
    'hi': {
      'Timetable': 'समय-सारणी',
      'Ramzan': 'रमजान',
      'Qibla': 'किबला',
      'Dua': 'दुआ',
      'Tasbih': 'तस्बीह',
      'Salatuk Options': 'सलातुक विकल्प',
      'Settings': 'सेटिंग्स',
      'Namaz Tarika': 'नमाज़ का तरीका',
      'Fatiha Ka Tarika': 'फ़ातिहा का तरीका',
      'Calendar': 'कैलेंडर',
      'About App': 'ऐप के बारे में',
      'Appearance': 'दिखावट',
      'Dark Mode': 'डार्क मोड',
      'Alarm & Times': 'अलार्म और समय',
      'Ring Adhan time': 'अज़ान के समय बजाएं',
      'Set Manual Prayer Times': 'मैनुअल प्रार्थना समय निर्धारित करें',
      'Prayer Notifications': 'प्रार्थना सूचनाएं',
      'Location updated': 'स्थान अपडेट किया गया',
      'Advanced Prayer Calculation': 'उन्नत नमाज़ गणना',
      'Calculation Method': 'गणना का तरीका',
      'Asr Method (Juristic)': 'असर का तरीका',
      'Hijri Date Adjustment': 'हिजरी तिथि समायोजन',
      '-2 Days': '-2 दिन',
      '-1 Day': '-1 दिन',
      '0 Days (No offset)': '0 दिन (कोई बदलाव नहीं)',
      '+1 Day': '+1 दिन',
      '+2 Days': '+2 दिन',
      'Not Set': 'सेट नहीं है',
      'Location: ': 'स्थान: ',
      'Fajr': 'फ़ज्र',
      'Sunrise': 'सूर्योदय',
      'Sunset': 'सूर्यास्त',
      'Dhuhr': 'ज़ुहर',
      'Asr': 'असर',
      'Maghrib': 'مग़रिब',
      'Isha': 'ईशा',
      'Jummah': 'जुम्मा',
      'Jumah': 'जुम्मा',
      'Sehr': 'सहर',
      'Iftar': 'इफ्तार',
      'Next Prayer': 'अगली नमाज़',
      'Manual Mode': 'मैनुअल मोड',
      'Hijri': 'हिजरी',
      'Reset': 'रीसेट',
      'Count': 'गिनती',
      'Total Count': 'कुल गिनती',
      'Daily Count': 'आज की गिनती',
      'Minus': 'घटाएं',
      'Ramzan Timetable': 'रमजान समय-सारणी',
      'SEHR': 'सहर',
      'IFTAR': 'इफ्तार',
      'Rakats Details:': 'रकात विवरण:',
      'Urdu Niyyat (نیت):': 'उर्दू नीयत (نیت):',
      'Hindi Niyyat (नीयत):': 'हिंदी नीयत (नीयत):',
      'PRAYER': 'नमाज़',
      'AZAN': 'अज़ान',
      'JAMAAT': 'जमात',
      'ENDS': 'अंत',
      'English': 'अंग्रेजी',
      'Reset Total Count?': 'कुल गिनती रीसेट करें?',
      'Are you sure you want to reset your lifetime tasbih progress?':
          'क्या आप वाकई अपनी जीवन भर की तस्बीह प्रोग्रेस को रीसेट करना चाहते हैं?',
      'Cancel': 'रद्द करें',
    },
  };
}
